version: '3'
services:
  api:
    container_name: flask-container
    build: .
    entrypoint: python app.py
    depends_on: 
     - db
    env_file:
      - .env
    ports:
      - '5000:5000'
    volumes:
      - .:/app
    networks:
      - app-network

  celery:
    build:
      context: .
      dockerfile: scheduler/Dockerfile
    command: celery  -A scheduler.celery_app worker -l info
    volumes:
      - ./scheduler:/scheduler
    depends_on:
      - db
      - redis
    networks:
      - app-network
      
  celery-beat:
    build: .
    command: celery -A scheduler.celery_app beat -l info
    volumes:
      - ./scheduler:/scheduler
    depends_on:
      - db
      - redis
      - celery
    networks:
      - app-network
  
  db:
    build: ./.docker/mysql
    restart: always
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - ./.docker/dbdata:/var/lib/mysql
      - ./.docker/mysql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - app-network

  redis:
    image: redis
    container_name: redis-container
    ports:
      - "6379:6379"
    networks:
      - app-network
  
#   rqmonitor:
#     image: pranavgupta1234/rqmonitor
#     ports:
#         - "8899:8899"
#     depends_on:
#       - redis
#     environment: 
#         - RQ_MONITOR_REDIS_URL=redis://redis:6379


networks:
    app-network:
        driver: bridge