version: '3'
services:
  api:
    container_name: flask-container
    build: .
    entrypoint: python app.py
    depends_on: 
     - db
    env_file:
      - .env
    ports:
      - '5000:5000'
    volumes:
      - .:/app
    networks:
      - app-network

  scheduler:
    build:
      context: .
      dockerfile: scheduler/Dockerfile
    links:
      - redis
  
  db:
    build: ./.docker/mysql
    restart: always
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - ./.docker/dbdata:/var/lib/mysql
      - ./.docker/mysql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - app-network

  redis:
    image: redis
    container_name: redis-container
    ports:
      - "6379:6379"
  
  rqmonitor:
    image: pranavgupta1234/rqmonitor
    ports:
        - "8899:8899"
    depends_on:
      - redis
    environment: 
        - RQ_MONITOR_REDIS_URL=redis://redis:6379


networks:
    app-network:
        driver: bridge